<a href="https://colab.research.google.com/github/claudiocdc/fifa-world-cup-analysis/blob/main/01_Limpieza_Fifa_WorldCup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
url = "https://raw.githubusercontent.com/claudiocdc/fifa-world-cup-analysis/main/WorldCups.csv"
df = pd.read_csv(url)
print(df.head())
print(df.info())

   Year      Country      Winner      Runners-Up    Third      Fourth  \
0  1930      Uruguay     Uruguay       Argentina      USA  Yugoslavia
1  1934        Italy       Italy  Czechoslovakia  Germany     Austria
2  1938       France       Italy         Hungary   Brazil      Sweden
3  1950       Brazil     Uruguay          Brazil   Sweden       Spain
4  1954  Switzerland  Germany FR         Hungary  Austria     Uruguay

   GoalsScored  QualifiedTeams  MatchesPlayed Attendance
0           70              13             18    590.549
1           70              16             17    363.000
2           84              15             18    375.700
3           88              13             22  1.045.246
4          140              16             26    768.607
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Year            20 non-null     int64
 1   Country         20 non-null     object
 2   Winner          20 non-null     object
 3   Runners-Up      20 non-null     object
 4   Third           20 non-null     object
 5   Fourth          20 non-null     object
 6   GoalsScored     20 non-null     int64
 7   QualifiedTeams  20 non-null     int64
 8   MatchesPlayed   20 non-null     int64
 9   Attendance      20 non-null     object
dtypes: int64(4), object(6)
memory usage: 1.7+ KB
None

In [3]:
#vemos que la asistencia son texto porque tienen el punto, la limpiamos para pasarlo a número
##Ojo! El regex = False sirve por si acaso, por eso lo pongo. En otras versiones de python , quizás lo trata como true y te borra todo, no solo el "."

df['Attendance'] = df['Attendance'].str.replace(".","",regex=False)
print(df.head())

   Year      Country      Winner      Runners-Up    Third      Fourth  \
0  1930      Uruguay     Uruguay       Argentina      USA  Yugoslavia
1  1934        Italy       Italy  Czechoslovakia  Germany     Austria
2  1938       France       Italy         Hungary   Brazil      Sweden
3  1950       Brazil     Uruguay          Brazil   Sweden       Spain
4  1954  Switzerland  Germany FR         Hungary  Austria     Uruguay

   GoalsScored  QualifiedTeams  MatchesPlayed Attendance
0           70              13             18     590549
1           70              16             17     363000
2           84              15             18     375700
3           88              13             22    1045246
4          140              16             26     768607

In [4]:
#cambiamos a número entero int
df['Attendance'] = df['Attendance'].astype(int)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Year            20 non-null     int64
 1   Country         20 non-null     object
 2   Winner          20 non-null     object
 3   Runners-Up      20 non-null     object
 4   Third           20 non-null     object
 5   Fourth          20 non-null     object
 6   GoalsScored     20 non-null     int64
 7   QualifiedTeams  20 non-null     int64
 8   MatchesPlayed   20 non-null     int64
 9   Attendance      20 non-null     int64
dtypes: int64(5), object(5)
memory usage: 1.7+ KB
None

In [5]:
#¿qué mundial lleno más estadios?
df.sort_values('Attendance',ascending = False).head()

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3587538
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3386810
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3359439
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3178856
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2785100

In [8]:
#sorprendente que con menos partidos hubiese mas asistencia que el de 2014 que tuvo mas partidos, suponemos que es por los estadios americanos
##vamos a ver realmente si fue por eso

df['Avg_Attendance'] = df['Attendance'] / df['MatchesPlayed']
df.sort_values('Avg_Attendance',ascending = False).head()

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance,Avg_Attendance
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3587538,68991.115385
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3386810,52918.906250
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3359439,52491.234375
8,1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95,16,32,1603975,50124.218750
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3178856,49669.625000

In [9]:
#¿Qué país ha ganado más Mundiales en la historia?

df['Winner'].value_counts()

Winner
Brazil        5
Italy         4
Germany FR    3
Uruguay       2
Argentina     2
England       1
France        1
Spain         1
Germany       1
Name: count, dtype: int64

In [14]:
#Lo de Alemania es un poco raro, habría que cambiarlo

df['Winner'] = df['Winner'].replace('Germany FR','Germany')
df['Winner'].value_counts()

Winner
Brazil       5
Italy        4
Germany      4
Uruguay      2
Argentina    2
England      1
France       1
Spain        1
Name: count, dtype: int64