<a href="https://colab.research.google.com/github/claudiocdc/fifa-world-cup-analysis/blob/main/01_Limpieza_Fifa_WorldCup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
url = "https://raw.githubusercontent.com/claudiocdc/fifa-world-cup-analysis/main/WorldCups.csv"
df = pd.read_csv(url)
print(df.head())
print(df.info())

   Year      Country      Winner      Runners-Up    Third      Fourth  \
0  1930      Uruguay     Uruguay       Argentina      USA  Yugoslavia
1  1934        Italy       Italy  Czechoslovakia  Germany     Austria
2  1938       France       Italy         Hungary   Brazil      Sweden
3  1950       Brazil     Uruguay          Brazil   Sweden       Spain
4  1954  Switzerland  Germany FR         Hungary  Austria     Uruguay

   GoalsScored  QualifiedTeams  MatchesPlayed Attendance
0           70              13             18    590.549
1           70              16             17    363.000
2           84              15             18    375.700
3           88              13             22  1.045.246
4          140              16             26    768.607
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Year            22 non-null     int64
 1   Country         22 non-null     object
 2   Winner          22 non-null     object
 3   Runners-Up      22 non-null     object
 4   Third           22 non-null     object
 5   Fourth          22 non-null     object
 6   GoalsScored     22 non-null     int64
 7   QualifiedTeams  22 non-null     int64
 8   MatchesPlayed   22 non-null     int64
 9   Attendance      22 non-null     object
dtypes: int64(4), object(6)
memory usage: 1.8+ KB
None

In [2]:
#vemos que la asistencia son texto porque tienen el punto, la limpiamos para pasarlo a número
##Ojo! El regex = False sirve por si acaso, por eso lo pongo. En otras versiones de python , quizás lo trata como true y te borra todo, no solo el "."

df['Attendance'] = df['Attendance'].str.replace(".","",regex=False)
print(df.head())

   Year      Country      Winner      Runners-Up    Third      Fourth  \
0  1930      Uruguay     Uruguay       Argentina      USA  Yugoslavia
1  1934        Italy       Italy  Czechoslovakia  Germany     Austria
2  1938       France       Italy         Hungary   Brazil      Sweden
3  1950       Brazil     Uruguay          Brazil   Sweden       Spain
4  1954  Switzerland  Germany FR         Hungary  Austria     Uruguay

   GoalsScored  QualifiedTeams  MatchesPlayed Attendance
0           70              13             18     590549
1           70              16             17     363000
2           84              15             18     375700
3           88              13             22    1045246
4          140              16             26     768607

In [3]:
#cambiamos a número entero int
df['Attendance'] = df['Attendance'].astype(int)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Year            22 non-null     int64
 1   Country         22 non-null     object
 2   Winner          22 non-null     object
 3   Runners-Up      22 non-null     object
 4   Third           22 non-null     object
 5   Fourth          22 non-null     object
 6   GoalsScored     22 non-null     int64
 7   QualifiedTeams  22 non-null     int64
 8   MatchesPlayed   22 non-null     int64
 9   Attendance      22 non-null     int64
dtypes: int64(5), object(5)
memory usage: 1.8+ KB
None

In [4]:
#¿qué mundial lleno más estadios?
df.sort_values('Attendance',ascending = False).head()

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3587538
21,2022,Qatar,Argentina,France,Croatia,Morocco,172,32,64,3404252
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3386810
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3359439
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3178856

In [5]:
#sorprendente que con menos partidos hubiese mas asistencia que el de 2014 que tuvo mas partidos, suponemos que es por los estadios americanos
##vamos a ver realmente si fue por eso

df['Avg_Attendance'] = df['Attendance'] / df['MatchesPlayed']
df.sort_values('Avg_Attendance',ascending = False).head()

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance,Avg_Attendance
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3587538,68991.115385
21,2022,Qatar,Argentina,France,Croatia,Morocco,172,32,64,3404252,53191.437500
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3386810,52918.906250
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3359439,52491.234375
8,1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95,16,32,1603975,50124.218750

In [6]:
#¿Qué país ha ganado más Mundiales en la historia?

df['Winner'].value_counts()

Winner
Brazil        5
Italy         4
Germany FR    3
Argentina     3
Uruguay       2
France        2
England       1
Spain         1
Germany       1
Name: count, dtype: int64

In [7]:
#Lo de Alemania es un poco raro, habría que cambiarlo

df['Winner'] = df['Winner'].replace('Germany FR','Germany')
df['Winner'].value_counts()

Winner
Brazil       5
Italy        4
Germany      4
Argentina    3
Uruguay      2
France       2
England      1
Spain        1
Name: count, dtype: int64

In [10]:
#Vamos a guardar la  tabla de partidos en otro dataframe

df_matches = pd.read_csv('https://raw.githubusercontent.com/claudiocdc/fifa-world-cup-analysis/refs/heads/main/WorldCupMatches.csv')
print(df_matches.head())
print(df_matches.info())

     Year              Datetime    Stage         Stadium         City  \
0  1930.0  13 Jul 1930 - 15:00   Group 1         Pocitos  Montevideo
1  1930.0  13 Jul 1930 - 15:00   Group 4  Parque Central  Montevideo
2  1930.0  14 Jul 1930 - 12:45   Group 2  Parque Central  Montevideo
3  1930.0  14 Jul 1930 - 14:50   Group 3         Pocitos  Montevideo
4  1930.0  15 Jul 1930 - 16:00   Group 1  Parque Central  Montevideo

  Home Team Name  Home Team Goals  Away Team Goals Away Team Name  \
0         France              4.0              1.0         Mexico
1            USA              3.0              0.0        Belgium
2     Yugoslavia              2.0              1.0         Brazil
3        Romania              3.0              1.0           Peru
4      Argentina              1.0              0.0         France

  Win conditions  Attendance  Half-time Home Goals  Half-time Away Goals  \
0                     4444.0                   3.0                   0.0
1                    18346.0                   2.0                   0.0
2                    24059.0                   2.0                   0.0
3                     2549.0                   1.0                   0.0
4                    23409.0                   0.0                   0.0

                  Referee               Assistant 1  \
0  LOMBARDI Domingo (URU)     CRISTOPHE Henry (BEL)
1       MACIAS Jose (ARG)  MATEUCCI Francisco (URU)
2     TEJADA Anibal (URU)   VALLARINO Ricardo (URU)
3   WARNKEN Alberto (CHI)       LANGENUS Jean (BEL)
4     REGO Gilberto (BRA)      SAUCEDO Ulises (BOL)

                  Assistant 2  RoundID  MatchID Home Team Initials  \
0         REGO Gilberto (BRA)    201.0   1096.0                FRA
1       WARNKEN Alberto (CHI)    201.0   1090.0                USA
2         BALWAY Thomas (FRA)    201.0   1093.0                YUG
3    MATEUCCI Francisco (URU)    201.0   1098.0                ROU
4  RADULESCU Constantin (ROU)    201.0   1085.0                ARG

  Away Team Initials
0                MEX
1                BEL
2                BRA
3                PER
4                FRA
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  852 non-null    float64
 1   Datetime              852 non-null    object
 2   Stage                 852 non-null    object
 3   Stadium               852 non-null    object
 4   City                  852 non-null    object
 5   Home Team Name        852 non-null    object
 6   Home Team Goals       852 non-null    float64
 7   Away Team Goals       852 non-null    float64
 8   Away Team Name        852 non-null    object
 9   Win conditions        852 non-null    object
 10  Attendance            850 non-null    float64
 11  Half-time Home Goals  852 non-null    float64
 12  Half-time Away Goals  852 non-null    float64
 13  Referee               852 non-null    object
 14  Assistant 1           852 non-null    object
 15  Assistant 2           852 non-null    object
 16  RoundID               852 non-null    float64
 17  MatchID               852 non-null    float64
 18  Home Team Initials    852 non-null    object
 19  Away Team Initials    852 non-null    object
dtypes: float64(8), object(12)
memory usage: 714.5+ KB
None

In [11]:
#attendance tiene menos, ¿Por qué? y hay muchas filas vacias ya que pone que hay 4572 entries cuando realmente hay solo rellenas 852
##Hay una función muy buena que es .dropna() https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html
###Segñun la docu el how ='all' permite borrar las que estan enteramente vacias y no solo las que tengan alguna vacía

df_matches = df_matches.dropna(how='all')
print(df_matches.info())

<class 'pandas.core.frame.DataFrame'>
Index: 852 entries, 0 to 851
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  852 non-null    float64
 1   Datetime              852 non-null    object
 2   Stage                 852 non-null    object
 3   Stadium               852 non-null    object
 4   City                  852 non-null    object
 5   Home Team Name        852 non-null    object
 6   Home Team Goals       852 non-null    float64
 7   Away Team Goals       852 non-null    float64
 8   Away Team Name        852 non-null    object
 9   Win conditions        852 non-null    object
 10  Attendance            850 non-null    float64
 11  Half-time Home Goals  852 non-null    float64
 12  Half-time Away Goals  852 non-null    float64
 13  Referee               852 non-null    object
 14  Assistant 1           852 non-null    object
 15  Assistant 2           852 non-null    object
 16  RoundID               852 non-null    float64
 17  MatchID               852 non-null    float64
 18  Home Team Initials    852 non-null    object
 19  Away Team Initials    852 non-null    object
dtypes: float64(8), object(12)
memory usage: 139.8+ KB
None

In [24]:
#¿Cuantos mundiales ha jugado cada país?
##Hay que juntar las veces que aparece tanto local como visitante para ver sus apariciones, luego usar la variable de año como indicador para contar cuantas veces aparecieron
###Aparte year esta en float y queda feo, vamos a cambiarlo a int
####Al ejecutar el código más adelante, vemos que hay nombres en sucio con valores como rn">Bosnia and Herzegovina	porlo que quitamos ese 'rn">'

df_matches["Home Team Name"] = df_matches["Home Team Name"].str.replace('rn">', '', regex=False)
df_matches["Away Team Name"] = df_matches["Away Team Name"].str.replace('rn">', '', regex=False)

df_matches['Year'] = df_matches['Year'].astype(int)
locales = df_matches[['Year','Home Team Name']].rename(columns={'Home Team Name':'Equipo'})
visitantes = df_matches[['Year','Away Team Name']].rename(columns={'Away Team Name':'Equipo'})
apariciones = pd.concat([locales, visitantes])
print(apariciones)

     Year       Equipo
0    1930       France
1    1930          USA
2    1930   Yugoslavia
3    1930      Romania
4    1930    Argentina
..    ...          ...
847  2014   Costa Rica
848  2014      Germany
849  2014    Argentina
850  2014  Netherlands
851  2014    Argentina

[1704 rows x 2 columns]

In [22]:
#Contamos las apariciones por año: agrupar por equipo, y de cada grupo cuántos años únicos tiene. Ojo con la n en el unique
##Confirmamos que Brazil es el que más mundiales ha ganado, también poruqe es el que más mundiales ha jugado

apariciones.groupby('Equipo')['Year'].nunique().sort_values(ascending=False)

Equipo
Brazil                  20
Italy                   18
Argentina               16
Mexico                  15
England                 14
                        ..
Togo                     1
United Arab Emirates     1
Ukraine                  1
Wales                    1
Zaire                    1
Name: Year, Length: 83, dtype: int64

In [29]:
# Consulta rápida: ¿cuántas veces apareció España?

consulta_pais = 'Spain'
filas_spain = apariciones[apariciones['Equipo'] == consulta_pais]
mundiales = filas_spain['Year'].nunique()
print('El país', consulta_pais, 'ha jugado', mundiales, 'Mundiales hasta 2014')

El país Spain ha jugado 14 Mundiales hasta 2014